/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UIdRouteImport } from './routes/u.$id'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as PartsIdRouteImport } from './routes/parts.$id'
import { Route as PartsIdEditRouteImport } from './routes/parts.$id_.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIdRoute = UIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RequestsRoute,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/parts/$id',
  path: '/parts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIdEditRoute = PartsIdEditRouteImport.update({
  id: '/parts/$id_/edit',
  path: '/parts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/my-requests': typeof MyRequestsRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parts/$id': typeof PartsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/u/$id': typeof UIdRoute
  '/parts/$id/edit': typeof PartsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/my-requests': typeof MyRequestsRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parts/$id': typeof PartsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/u/$id': typeof UIdRoute
  '/parts/$id/edit': typeof PartsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/my-requests': typeof MyRequestsRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parts/$id': typeof PartsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/u/$id': typeof UIdRoute
  '/parts/$id_/edit': typeof PartsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/my-requests'
    | '/requests'
    | '/reset-password'
    | '/sell'
    | '/sitemap.xml'
    | '/parts/$id'
    | '/requests/$id'
    | '/u/$id'
    | '/parts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/my-requests'
    | '/requests'
    | '/reset-password'
    | '/sell'
    | '/sitemap.xml'
    | '/parts/$id'
    | '/requests/$id'
    | '/u/$id'
    | '/parts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/my-requests'
    | '/requests'
    | '/reset-password'
    | '/sell'
    | '/sitemap.xml'
    | '/parts/$id'
    | '/requests/$id'
    | '/u/$id'
    | '/parts/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  MyRequestsRoute: typeof MyRequestsRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PartsIdRoute: typeof PartsIdRoute
  UIdRoute: typeof UIdRoute
  PartsIdEditRoute: typeof PartsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$id': {
      id: '/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof UIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/parts/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$id_/edit': {
      id: '/parts/$id_/edit'
      path: '/parts/$id/edit'
      fullPath: '/parts/$id/edit'
      preLoaderRoute: typeof PartsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RequestsRouteChildren {
  RequestsIdRoute: typeof RequestsIdRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsIdRoute: RequestsIdRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  MyRequestsRoute: MyRequestsRoute,
  RequestsRoute: RequestsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PartsIdRoute: PartsIdRoute,
  UIdRoute: UIdRoute,
  PartsIdEditRoute: PartsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
