
ALTER TABLE public.oem_zip_jobs
  ADD COLUMN IF NOT EXISTS files_seen INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS files_parsed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS storage_uploaded INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS db_inserted INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS storage_failed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS db_failed INTEGER NOT NULL DEFAULT 0;
